### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by extrastu** [electron-modules/electron-windows-titlebar#14]
按照文档使用，无法正常使用，变异报错

```
const windowTitleBar = require('electron-windows-titlebar');
const win = new BrowserWindow({
  width: 800,
  height: 600,
  title: 'addon demo',
})
const hwnd = win?.getNativeWindowHandle();
const setDark = true;
if (hwnd) {
  setDark ? windowTitleBar.switchDarkMode(hwnd) : windowTitleBar.switchLightMode(hwnd);
}
```

![image](https://user-images.githubusercontent.com/19451694/228476574-9c6b409b-3ade-43ba-9332-520963944f16.png)

**Comment by xudafeng** [comment]
node 16 版本以上试试

**Comment by sriting** [comment]
能截个全图看看吗？看不到具体报错的位置呢
![image](https://user-images.githubusercontent.com/17586742/228742932-045c3dd4-99c5-4230-931e-b57ad1b34eed.png)

**Comment by extrastu** [comment]
![捕获](https://user-images.githubusercontent.com/19451694/228747228-b40eb3aa-3a78-464b-8b57-e5b0ccb5a51d.PNG)

@sriting

**Comment by sriting** [comment]
可以看类似 issue [https://github.com/TooTallNate/node-bindings/issues/54](url) 可能是和你 webpack 配置有关，binding 找不到路径抛出的错误。
在 npm i 后，electron-windows-titlebar 会构建好一个二进制文件：electron-windows-titlebar.node
![image](https://user-images.githubusercontent.com/17586742/229266391-d2e02291-df00-4be1-b148-6a2f58c51720.png)
你可以尝试直接引入二进制文件来看看是否能正常使用
```
import windowTitleBar from 'electron-windows-titlebar/build/Release/electron-windows-titlebar';
// 或 const windowTitleBar = require('electron-windows-titlebar/build/Release/electron-windows-titlebar');
```
能正常使用的话，需要你检查下你项目的路径配置看问题出在哪了。


另外，我们有一个 sample 项目包含了所有我们开源包的 demo，感兴趣可以看看：

https://github.com/electron-modules/electron-modules-sample

![image](https://user-images.githubusercontent.com/17586742/229266801-2f853369-7d0d-46a5-b25f-0eb5d2ccf921.png)

**Comment by extrastu** [comment]
```
import windowTitleBar from 'electron-windows-titlebar/build/Release/electron-windows-titlebar';
// 或 const windowTitleBar = require('electron-windows-titlebar/build/Release/electron-windows-titlebar')
```

测试了下，都不能正常使用，提示找不到依赖

**Comment by sriting** [comment]
删掉node_modules，然后重新npm i一下，看看有没有报错信息？
npm i安装好以后，看看node_modules/electron-windows-titlebar/build/Release有没有存在编译的二进制文件？

**Comment by extrastu** [comment]
> 删掉node_modules，然后重新npm i一下，看看有没有报错信息？ npm i安装好以后，看看node_modules/electron-windows-titlebar/build/Release有没有存在编译的二进制文件？

![捕获1](https://user-images.githubusercontent.com/19451694/229268187-7ac5511b-824d-4ef2-9e7c-9807730c6e2f.PNG)

PS: node 版本是16.17

**Comment by sriting** [comment]
> ```
> 
> import windowTitleBar from 'electron-windows-titlebar/build/Release/electron-windows-titlebar';
> 
> // 或 const windowTitleBar = require('electron-windows-titlebar/build/Release/electron-windows-titlebar')
> 
> ```
> 
> 
> 
> 测试了下，都不能正常使用，提示找不到依赖

能截图看看具体报错吗？

**Comment by extrastu** [comment]
![捕获3](https://user-images.githubusercontent.com/19451694/229268454-bd769b93-f681-46e8-802c-a78ea0dd6cbc.PNG)

**Comment by sriting** [comment]
> ![捕获3](https://user-images.githubusercontent.com/19451694/229268454-bd769b93-f681-46e8-802c-a78ea0dd6cbc.PNG)
> 
> 

看报错还是引用路径的问题
引用路径加上.node文件后缀试试？

**Comment by extrastu** [comment]
加了.node 报其他的错误了
![捕4获](https://user-images.githubusercontent.com/19451694/229268807-368edfb8-4832-4ca7-8160-17e05ea2f0b2.PNG)

**Comment by sriting** [comment]
> 加了.node 报其他的错误了
> 
> ![捕4获](https://user-images.githubusercontent.com/19451694/229268807-368edfb8-4832-4ca7-8160-17e05ea2f0b2.PNG)
> 
> 

看错误信息写的很明显啦，webpack没有合适loader去加载，看起来还是你的webpack配置问题哦

**Comment by sriting** [comment]
看看 webpack node-loader
https://webpack.js.org/loaders/node-loader/
