### ISSUE TITLE
怎么在vite 项目里导入，现在报错

### ISSUE THREAD

**Issue by xu455255849** [electron-modules/electron-windows-titlebar#15]
Could not dynamically require "/Users/xushaoping/Documents/new-person/electron-vite-project/build/electron-windows-titlebar.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

**Comment by xu455255849** [comment]
貌似ts支持也不好，有类型错误

**Comment by sriting** [comment]
目前暂没有支持Vite。有个类似的问题讨论，可以参考看看
https://github.com/rollup/plugins/discussions/1416

**Comment by xu455255849** [comment]
今天查了下文档 electron v22 以后 windows 也天然支持 暗黑模式，效果不错 我把electron 升级上来了
